### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by matthewgertner** [Blacksuan19/scrapy-ai#6]
https://github.com/Blacksuan19/scrapy-ai/blob/142f71367282d4f2e6381ab3f4f1cc9f74aa9788/scrapy_llm/handler.py#L66

Did you mean to put "dorm data" here? I might be missing something obvious but I couldn't figure out what it means.

**Comment by Blacksuan19** [comment]
good catch! should be just data, this project initially started as the example project dorm scrapper than I refactored out most of the functionality.

**Comment by Blacksuan19** [comment]
closed in #5
